perviy-commit
Di-gitcode/brbrshp pull request #1
Opened 2019-12-08 09:22 UTC by Di-gitcode

2020-01-13 20:06 UTC, saintgeo23 requested changes
Очень и очень неплохо! Молодчина! Моя первая верстка была намного хуже)))

Вот пара моментов:
- в магазине радио-кнопки не работают как радио-кнопки (активна должна быть только 1);
- в магазине не выделена активная страница;
- в магазине не работает переход на страницу item.html. Каждая карточка товара должна быть ссылкой на соответствующую страницу товара, но макет только на 1, но и на нее ссылки нет);
- что-то очень странное у тебя с табуляцией и с отступами, очень много ненужных пробелов между строками и между блоками, убирай их.

Попробуй исправить. Будут вопросы - пиши.

2020-01-13 20:06 UTC, saintgeo23 commented on css/styles.css
> +	margin: 0;
во фронте лучше все отступы делать в 2 пробела

2020-01-13 20:06 UTC, saintgeo23 commented on css/styles.css
> +
не надо пустых строк в блоке

2020-01-13 20:06 UTC, saintgeo23 commented on css/styles.css
> +
не надо таких огромных пропусков

2020-01-13 20:06 UTC, saintgeo23 commented on css/styles.css
> +    align-content: center;
разные отступы

2020-01-13 20:06 UTC, saintgeo23 commented on css/styles.css
> +
между блоками - 1 пустая строка.
отступы и пропуски нужно поправить во всем файле

2020-01-13 20:06 UTC, saintgeo23 commented on css/styles.css
> +nav > div > a:active {
почему ты сперва слушаешь `nav > div:active` а потом `nav > div > a:active`?
Объединяй все стили для `:active` и применяй к `nav > div > a:active`

2020-01-13 20:06 UTC, saintgeo23 commented on css/styles.css
> +		0 0 44px 0px #000000,
странная табуляция. пиши в 1 строку все

2020-01-13 20:06 UTC, saintgeo23 commented on css/styles.css
> +nav .barbershopSignature {
классы обычно именуются кебаб-кейсом `barbershop-signature`

2020-01-13 20:06 UTC, saintgeo23 commented on css/styles.css
> +	left: -191px;
какой-то странный хак. для чего он?

2020-01-13 20:06 UTC, saintgeo23 commented on css/styles.css
> +/* not working */
то, что `not working` и оставлять в коде не нужно

2020-01-13 20:06 UTC, saintgeo23 commented on css/styles.css
> +/* not working */
не работает, потому что тень ты выше установила для `nav > div > a:active`, а убираешь ее для `nav > div.barbershopSignature:active`

2020-01-13 20:06 UTC, saintgeo23 commented on css/styles.css
> +	left: 1101px;
это грязь.
чтобы таких страшных цифр не было, можно сделать хак:
```css
position: relative;
left: 50%;
transform: translateX(-50%);
```

2020-01-13 20:06 UTC, saintgeo23 commented on css/styles.css
> +	left: 1101px;
или просто контейнеру картинки можешь дать `text-align: center;` и тогда никаких абсолютов с координатами не придется давать

2020-01-13 20:06 UTC, saintgeo23 commented on css/styles.css
> +	left: -110px;
опять какая-то шляпа.
тебе нужно было положить это в контейнер, которому задать максимальную ширину, и потом выровнять его по центру при помощи `margin-left: auto; margin-right: auto;`

2020-01-13 20:06 UTC, saintgeo23 commented on css/styles.css
> +	right: -100px;
та же бяка

2020-01-13 20:06 UTC, saintgeo23 commented on css/styles.css
> +	right: -180px;
бяка

2020-01-13 20:06 UTC, saintgeo23 commented on css/styles.css
> +	right: -180px;
бяка

2020-01-13 20:06 UTC, saintgeo23 commented on css/styles.css
> +	margin: 300px auto 50px auto;
во! тут у тебя отцентрировано

2020-01-13 20:06 UTC, saintgeo23 commented on css/styles.css
> +	filter: invert(100%);
в IE фильтры не работают вообще

2020-01-13 20:06 UTC, saintgeo23 commented on css/styles.css
> +	z-index: -1;
зачем -1?

2020-01-13 20:06 UTC, saintgeo23 commented on index.html
> +
с отступами - какая-то дичь.
правь во всем документе

2020-01-13 20:06 UTC, saintgeo23 commented on index.html
> +						<div><a href="#">Информация</a></div>
это должны быть не дивы, а li внутри ul, который можно засунуть внутрь nav

2020-01-13 20:06 UTC, saintgeo23 commented on index.html
> +						<button class="entryButtonMainPage"><img src="img/login.png">Вход</button>
у img обязательно должен быть alt

2020-01-13 20:06 UTC, saintgeo23 commented on index.html
> +							<h2>БЫСТРО</h2>
текст всегда должен быть написать обычным шрифтом, а свойствами его потом нужно делать в капс

2020-01-13 20:06 UTC, saintgeo23 commented on item.html
> +								<img src="img\Layer_47_copy.png" class="big">
вот здесь чет верстка поехала. разберись

2020-01-13 20:06 UTC, saintgeo23 commented on item.html
> +								<img src="img\Layer_47_copy.png" class="big">
вот примерно как должно выглядеть 
![image](https://user-images.githubusercontent.com/11259279/72287450-2391c880-3658-11ea-91b8-25deee4d91c5.png)

2020-01-13 20:06 UTC, saintgeo23 commented on item.html
> +									<img src="img\Layer_45.png" class="small">
имена файлам лучше было давать более осознанные

2020-01-13 20:06 UTC, saintgeo23 commented on shop.html
> +								<input type="radio" name="goodGroup1" value="razor" id="razor" class="radio">
чтобы они работали вместе, у них должен быть одинаковый name, а не разный

2020-01-13 20:06 UTC, saintgeo23 commented on shop.html
> +							<!--
все закомментированные участки кода перед пулл-реквестом удаляются

2020-01-13 20:06 UTC, saintgeo23 commented on shop.html
> +							<!--
и да, это должны были быть li внутри ul

2020-01-14 09:06 UTC, Di-gitcode commented on css/styles.css
> +	margin: 0;
* {
  margin: 0;

слишком большой отступ? так должно быть?

2020-01-14 09:13 UTC, Di-gitcode commented on css/styles.css
> +
между блоками должна быть всего одна пустая строка или ее быть не должно?

2020-01-14 09:33 UTC, Di-gitcode commented on css/styles.css
> +nav > div > a:active {
nav > div > a:active меняет фон только у надписи, а надо на весь блок

![active](https://user-images.githubusercontent.com/56671389/72331781-cfbfc780-36c9-11ea-9257-aa0897de8605.png)
слева с моим разделением, справа как ты советуешь. кстати, тут я не смогла сделать линию нужной толщины, как в макете

2020-01-14 09:42 UTC, saintgeo23 commented on css/styles.css
> +	margin: 0;
должно быть 2 пробела. я в настройках ставлю tab = 2 spaces.
каждый новый уровень - на 2 пробела правее.
например:
```less
.one {
  position: relative;

  &__underlay {
    position: absolute;
    top: 0;
    left: 0;
  }
}
```

2020-01-14 09:44 UTC, saintgeo23 commented on css/styles.css
> +
1 строка между блоками

2020-01-14 09:49 UTC, saintgeo23 commented on css/styles.css
> +nav > div > a:active {
значит нужно сделать `a` размером с `div`.
если нужно, чтобы подчеркнуто должно быть только слово - ставь его в спан и давай стили.
но слушать это все должно только 1 состояние
```
nav > div > a:active {
  box-shadow: none;
}

nav > div > a:hover > span,
nav > div > a:active > span, {
  border-bottom: 5px solid #fff;
}
```

и подчеркивание там не на состоянии нажатия, а на активной ссылке

2020-01-14 10:02 UTC, Di-gitcode commented on css/styles.css
> +	margin: 0;
поняла, спасибо

2020-01-14 10:03 UTC, Di-gitcode commented on css/styles.css
> +
ок, исправляю

2020-01-14 10:16 UTC, Di-gitcode commented on css/styles.css
> +nav > div > a:active {
как задать размер для `nav > div > a`, если у div нет заданной ширины, все зависит от размера контента?

>если нужно, чтобы подчеркнуто должно быть только слово - ставь его в спан и давай стили
`<div><a href="price.html"><span>Прайс-лист</span></a></div>` я правильно поняла? с таким исправлением + с твоим кодом ниже подчеркивания этого пункта меню на странице с прайс-листом нет
>

2020-01-14 10:28 UTC, Di-gitcode commented on css/styles.css
> +	left: -191px;
чтобы подвинуть пункты меню влево на главной странице, когда лого нет

2020-01-14 10:38 UTC, saintgeo23 commented on css/styles.css
> +	left: -191px;
Это делается не так.
Задай такие стили, чтобы весь контент контейнера двигался влево, если лого нет. и тогда не надо будет задавать эти страшные цифры

2020-01-14 14:32 UTC, Di-gitcode commented on css/styles.css
> +	filter: invert(100%);
тогда в графическом редакторе менять картинку?

2020-01-14 14:36 UTC, Di-gitcode commented on css/styles.css
> +	z-index: -1;
на сайте, откуда брала пример для переделки, говорится, что это визуально убирает элемент

2020-01-14 14:38 UTC, Di-gitcode commented on index.html
> +						<div><a href="#">Информация</a></div>
сначала делала списком, потом где-то увидела, что дивами надо делать)

2020-01-14 14:39 UTC, saintgeo23 commented on css/styles.css
> +	filter: invert(100%);
да, подтягивай 2. с прозрачным фоном. фон у кнопки меняй через css

2020-01-14 14:39 UTC, saintgeo23 commented on css/styles.css
> +	z-index: -1;
не надо этого. ставь `display: none;`

2020-01-14 14:40 UTC, saintgeo23 commented on index.html
> +						<div><a href="#">Информация</a></div>
больше не смотри туда)

2020-01-14 15:03 UTC, Di-gitcode commented on shop.html
> +							<!--
т.е. дивы надо было положить внутрь списка вот так? `<li><div><img>.........</li>`

2020-01-14 15:09 UTC, saintgeo23 commented on shop.html
> +							<!--
можно так, а можно заменить `div` на `li`

2020-01-28 10:20 UTC, saintgeo23 approved these changes
Стало намного лучше.
Вопрос с отступами осталось немного поправить.
Как поправишь - можешь мерджить. Остальное, если встретиться, - поправишь в другой ветке.

2020-01-28 10:20 UTC, saintgeo23 commented on css/styles.css
> +
пустая строка)

2020-01-28 10:20 UTC, saintgeo23 commented on css/styles.css
> +}
в конце файла всегда должна быть пустая строка. но только 1

2020-01-28 10:20 UTC, saintgeo23 commented on index.html
> +					<ul class="menu main-page">
неправильные отступы.
во-первых: отступы лучше делать в 1 таб или 2 пробела. но сразу определись: у тебя пробелы или таб. комбинировать их не надо.
во-вторых: они у тебя почему-то совсем разные.
```html
<body>
		<header> <!-- 2 таба -->
		  <div class="wrapper"> <!-- 2 таба 2 пробела -->
			  <div class="navigation"> <!-- 3 таба 2 пробела -->
					<ul class="menu main-page"> <!-- 5 табов -->
```
а должно быть
```html
<body>
	<header> <!-- 1 таб -->
		<div class="wrapper"> <!-- 2 таба -->
			<div class="navigation"> <!-- 3 таба -->
				<ul class="menu main-page"> <!-- 4 таба -->
```

2020-01-28 10:20 UTC, saintgeo23 commented on index.html
> +</html>
добавь пустую строку

2020-01-28 10:20 UTC, saintgeo23 commented on item.html
> +</html>
и тут

2020-01-28 10:20 UTC, saintgeo23 commented on price.html
> +	</html>
и тут

2020-01-28 10:20 UTC, saintgeo23 commented on shop.html
> +		</html>
и тут.
но тут еще почему-то закрывающая часть html уехала вправо сильно.
а ведь это тег самого первого уровня, т.е. смещения вообще не должно быть

2020-01-29 21:34 UTC, merged