BBS-01. Changed alt for gallery images
Di-gitcode/brbrshp pull request #2
Opened 2020-01-30 06:26 UTC by Di-gitcode

2020-02-03 16:08 UTC, saintgeo23 requested changes
Немного доработать вложенность классов

2020-02-03 16:08 UTC, saintgeo23 commented on css/styles.css
> +  height: inherit;
если ты задала высоту где-то уже, то лучше дальше по вложенности писать `height: 100%`

2020-02-03 16:08 UTC, saintgeo23 commented on css/styles.css
> +  display: flex;
у тебя в самом блоке уже задано это правило. зачем в модификаторе дублировать. если ничего не меняется, то и модификатор не нужен.
у тебя просто будет
`<div class="header__menu" />`
и
`<div class="header__menu header__menu_with-logo" />`

2020-02-03 16:08 UTC, saintgeo23 commented on css/styles.css
>    display: flex;
дублировать в модификаторе не нужно, если ты не переопределяешь или не восстанавливаешь.

2020-02-03 16:08 UTC, saintgeo23 commented on css/styles.css
> +.header__menu-item-link {
здесь уже можно сделать полноценный новый блок `.header-link`
у тебя получится, что в блоке-родителе у тебя обертка над этим есть, которая его позиционирует, а этот блок будет отдельным, будет задавать свое отображение уже.

2020-02-03 16:08 UTC, saintgeo23 commented on css/styles.css
> +.header__menu-item-name {
дальше писать не буду, но вот это все уже можно запихнуть в блок `.header-link`.
будет дальше `.header-link__name`, `.header-link__label` и тд

2020-02-03 16:08 UTC, saintgeo23 commented on css/styles.css
> +.header__menu-item-name {
просто мы дальше будем разбивать это все на компоненты, а компоненты должны быть достаточно короткими. лучше в компонент `header` вложить 10 мелких

2020-02-04 09:03 UTC, Di-gitcode commented on css/styles.css
> +  display: flex;
flex для `<div class="header__menu" />` "растаскивает по углам" кнопки меню и кнопку входа, а модификаторы уже влияют на расположение самих кнопок меню

2020-02-04 09:08 UTC, saintgeo23 commented on css/styles.css
> +  display: flex;
ну и растаскивай. зачем стили повторять?

2020-02-04 09:08 UTC, Di-gitcode commented on css/styles.css
> +.header__menu-item-link {
то есть заменить такое написание
`<li class="header__menu-item"><a class="header__menu-item-link" href="javascript:;"><span class="header__menu-item-name">Контакты</span></a></li>`

на такое?
`<li class="header__link"><a class="header__link-referal" href="javascript:;"><span class="header__link-name">Контакты</span></a></li>`

2020-02-04 09:12 UTC, saintgeo23 commented on css/styles.css
> +.header__menu-item-link {
нет.
на такое
```html
<li class="header__link">
  <a class="header-link" href="javascript:;">
    <span class="header-link__name">Контакты</span>
  </a>
</li>
```

2020-02-04 09:15 UTC, Di-gitcode commented on css/styles.css
> +  display: flex;
ты имеешь в виду, что зря flex прописываю и для <div class="header__menu" /> и для `<div class="header__menu header__menu_with-logo" />`? я, наверное, зря прописала это как модификатор, это вообще же к списку относится, а не к блоку. заменю на `<div class="header__menu header__menu-with-logo" />

2020-02-04 09:25 UTC, Di-gitcode commented on css/styles.css
> +.header__menu-item-link {
ок. я думала, название класса обязательно должно начинаться с названия "главного блока" и двойного нижнего подчеркивания

2020-02-04 12:10 UTC, saintgeo23 commented on css/styles.css
> +.header__menu-item-link {
я об этом и говорю. мы потом разобьем код на компоненты. они будут в разных файлах. и в каждом файле будет свой единственный блок

2020-02-04 12:10 UTC, saintgeo23 commented on css/styles.css
> +.header__menu-item-link {
такое отделение сейчас - потом проще разбивать. сейчас у тебя в файле не обязательно 1 блок

2020-02-04 12:11 UTC, saintgeo23 commented on css/styles.css
> +  display: flex;
такого не может быть тогда
на одном диве классы разных элементов

2020-02-04 13:30 UTC, Di-gitcode commented on css/styles.css
> +  display: flex;
```
<div class="header__menu">
  <ul class="header__menu-with-logo" />
</div>
```

некорректно будет?

2020-02-04 13:51 UTC, saintgeo23 commented on css/styles.css
> +  display: flex;
нет.
тогда переименовывать надо.
```html
<div class="header__menu">
  <ul class="header__menu-box" />
</div>
```

2020-02-07 09:28 UTC, saintgeo23 requested changes
Немного еще подправить

2020-02-07 09:28 UTC, saintgeo23 commented on css/styles.css
>    flex-direction: row;
row идет по умолчанию. можно было не указывать.
вообще пойми смысл модификатора:
- у тебя есть к примеру элемент,
- у элемента есть стили, например
```css
.header__menu-box {
  display: block;
}
```
- этот элемент используется еще в одном месте, и там, в этом месте, в нем есть еще и логотип,
- тебе нужно изменить стили для этого второго места - ты даешь там классы `header__menu-box header__menu-box_with-logo` и определяешь стили для модификатора, например
```css
.header__menu-box_with-logo {
  display: flex;
  align-items: center;
}
```

то-есть в стилях модификатора ты должна давать новые стили и/или переопределять старые, которые в модификаторе должны быть другими.

2020-02-07 09:28 UTC, saintgeo23 commented on css/styles.css
> +.header-link__logo {
вроде бы это должно быть несколькими блоками ниже

2020-02-07 09:28 UTC, saintgeo23 commented on css/styles.css
> +  margin-bottom: 30px;
вот такие марджины лучше задавать через плюс.
ведь у тебя этот марджин может меняться в зависимости от того, что будет идти после этого элемента. а вдруг у тебя ничего не будет идти и тебе не нужен будет этот марджин - придется отменять.
в общем, правило такое: если даешь марджины между соседними элементами, лучше давать его второму из них.
то-есть вместо
```css
.main-plate-side__headline {
  margin-bottom: 30px;
}
```
лучше сделать
```css
.main-plate-side__headline + .main-plate-side__news {
  margin-top: 30px;
}
```
исключением является случай, когда тебе нужно расположить много элементов на странице сеткой и чтобы они сами переносились на новую строку. тогда тебе нужно будет давать верхний и правый марджин самому элементу, а не его соседям через плюс

2020-02-07 09:28 UTC, saintgeo23 commented on css/styles.css
> +.main__headline {
элементы блока `.main` были выше

2020-02-07 09:28 UTC, saintgeo23 commented on index.html
> +					<p class="footer__text footer__text_position-center">Разработано:</p>
html я не смотрел. у меня это выглядит вот так
![image](https://user-images.githubusercontent.com/11259279/74017390-3a9caf80-49a5-11ea-8461-f2f4430c84ce.png)
нечитаемый пиздец. что у тебя в настройках редактора по поводу отступов?

2020-02-07 09:59 UTC, Di-gitcode commented on index.html
> +					<p class="footer__text footer__text_position-center">Разработано:</p>
про отступы только это нашла. настройки с прошлого раза вроде не меняла. у тебя только футер так выглядит?

![spaces](https://user-images.githubusercontent.com/56671389/74019927-923d1a00-49a9-11ea-9215-b9d55473dba3.jpg)

2020-02-07 10:01 UTC, Di-gitcode commented on css/styles.css
> +.main__headline {
это уже относится к другой странице, или все равно прописывать, где первые `main__`?

2020-02-07 10:01 UTC, Di-gitcode commented on css/styles.css
> +  margin-bottom: 30px;
хорошо

2020-02-07 10:03 UTC, Di-gitcode commented on css/styles.css
> +.header-link__logo {
да, спасибо!

2020-02-07 10:12 UTC, Di-gitcode commented on css/styles.css
>    flex-direction: row;
в самом начале без дублирования
`flex-direction: row;
  align-content: flex-start;
  overflow: hidden;`

логотип и меню располагались не так, как нужно. наверное, сейчас что-то уже подкручено, поэтому и без этого работает. так-то про смысл модификаторов, вроде, понятно

2020-02-08 12:34 UTC, merged